### ISSUE TITLE
opera driver issue: Invalid service list received

### ISSUE THREAD

**Issue by yanshuai** [operasoftware/operaprestodriver#105]
hi, all, when I create opera driver, it throws exception:

```
Caused by: java.lang.IllegalStateException: Invalid service list received
    at com.opera.core.systems.scope.stp.StpConnection.parseServiceList(StpConnection.java:343)
    at com.opera.core.systems.scope.stp.StpConnection.readMessage(StpConnection.java:387)
    at com.opera.core.systems.scope.stp.StpConnection.canRead(StpConnection.java:265)
    at com.opera.core.systems.internal.SocketMonitor.processSelectionKey(SocketMonitor.java:212)
    at com.opera.core.systems.internal.SocketMonitor.pollSockets(SocketMonitor.java:134)
    at com.opera.core.systems.internal.SocketMonitor.poll(SocketMonitor.java:108)
    at com.opera.core.systems.scope.stp.StpThread.run(StpThread.java:58)
```

the service list message I got from memory through debuging is as follows:
??GET / HTTP/1.1
Host: 127.0.0.1:39623
Connection: keep-alive
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,_/_;q=0.8
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.122 Safari/537.36 OPR/24.0.1558.64
Accept-Encoding: gzip,deflate,lzma,sdch
Accept-Language: zh-CN,zh;q=0.8
(..)

**Comment by lkende** [comment]
Can't use with Opera > 12.  We are all waiting on Opera to support WebDriver with Blink engine.  When will that happen?  Opera team appears to be pretty quiet about it, so who knows.

**Comment by cynthia** [comment]
I think this is what you want: https://github.com/operasoftware/operachromiumdriver

**Comment by cynthia** [comment]
Feel free to reopen in case that does not satisfy what you need! I'll close this for now.
