### ISSUE TITLE
since 2.44.0, unable to start a session with exception : Error for /wd/hub/session java.lang.NoClassDefFoundError: org/json/JSONObject

### ISSUE THREAD

**Issue by ychab** [operasoftware/operaprestodriver#106]
Hi,

Since 2.44.0 release of selenium standalone server, unable to start a session with opera 12.16 on Linux with exception : 

> 12:25:03.666 WARN - Error for /wd/hub/session
> java.lang.NoClassDefFoundError: org/json/JSONObject
>     at java.lang.Class.getDeclaredMethods0(Native Method)
>     at java.lang.Class.privateGetDeclaredMethods(Class.java:2688)
>     at java.lang.Class.privateGetMethodRecursive(Class.java:3035)
>     at java.lang.Class.getMethod0(Class.java:3005)
>     at java.lang.Class.privateGetMethodRecursive(Class.java:3045)
>     at java.lang.Class.getMethod0(Class.java:3005)
>     at java.lang.Class.privateGetMethodRecursive(Class.java:3045)
>     at java.lang.Class.getMethod0(Class.java:3005)
>     at java.lang.Class.getMethod(Class.java:1771)
>     at org.openqa.selenium.remote.BeanToJsonConverter.getMethod(BeanToJsonConverter.java:224)
>     at org.openqa.selenium.remote.BeanToJsonConverter.convertObject(BeanToJsonConverter.java:177)
>     at org.openqa.selenium.remote.BeanToJsonConverter.convertObject(BeanToJsonConverter.java:137)
>     at org.openqa.selenium.remote.BeanToJsonConverter.mapObject(BeanToJsonConverter.java:262)
>     at org.openqa.selenium.remote.BeanToJsonConverter.convertObject(BeanToJsonConverter.java:216)
>     at org.openqa.selenium.remote.BeanToJsonConverter.convertObject(BeanToJsonConverter.java:84)
>     at org.openqa.selenium.remote.BeanToJsonConverter.convert(BeanToJsonConverter.java:64)
>     at org.openqa.selenium.remote.http.JsonHttpResponseCodec.encode(JsonHttpResponseCodec.java:44)
>     at org.openqa.selenium.remote.server.JsonHttpCommandHandler.handleRequest(JsonHttpCommandHandler.java:185)
>     at org.openqa.selenium.remote.server.DriverServlet.handleRequest(DriverServlet.java:201)
>     at org.openqa.selenium.remote.server.DriverServlet.doPost(DriverServlet.java:163)
>     at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
>     at org.openqa.selenium.remote.server.DriverServlet.service(DriverServlet.java:129)
>     at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
>     at org.openqa.jetty.jetty.servlet.ServletHolder.handle(ServletHolder.java:428)
>     at org.openqa.jetty.jetty.servlet.ServletHandler.dispatch(ServletHandler.java:680)
>     at org.openqa.jetty.jetty.servlet.ServletHandler.handle(ServletHandler.java:571)
>     at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1526)
>     at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1479)
>     at org.openqa.jetty.http.HttpServer.service(HttpServer.java:920)
>     at org.openqa.jetty.http.HttpConnection.service(HttpConnection.java:820)
>     at org.openqa.jetty.http.HttpConnection.handleNext(HttpConnection.java:986)
>     at org.openqa.jetty.http.HttpConnection.handle(HttpConnection.java:837)
>     at org.openqa.jetty.http.SocketListener.handleConnection(SocketListener.java:243)
>     at org.openqa.jetty.util.ThreadedServer.handle(ThreadedServer.java:358)
>     at org.openqa.jetty.util.ThreadPool$PoolThread.run(ThreadPool.java:537)
> Caused by: java.lang.ClassNotFoundException: org.json.JSONObject
>     at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
>     at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
>     at java.security.AccessController.doPrivileged(Native Method)
>     at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
>     at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
>     at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
>     at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
>     ... 35 more

Was working great with 2.43.1.
Thanks

**Comment by am-karl** [comment]
same on OSX, any known solutions to this?

**Comment by cynthia** [comment]
Have you tried adding one of the release JARs from here in your classpath?
http://mvnrepository.com/artifact/org.json/json
