### ISSUE TITLE
Does Operadriver support WebDriver alert api

### ISSUE THREAD

**Issue by lintaonz** [operasoftware/operaprestodriver#31]
Hi,

I am using selenium-server-standalone-2.8.0 with DotNet webdriver 2.8. And I tested both on Opera 11.50 and 11.51, it seems Operadriver cannot handle javascript alert popup window. The follow line is always  throw exception:

Driver.SwitchTo().Alert();

---

System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
  ----> System.InvalidOperationException : No response in a timely fashion.
Build info: version: '2.8.0', revision: '14056', time: '2011-10-06 12:41:26'
System info: os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.6.0_29'
Driver info: driver.version: OperaDriver
    at System.RuntimeMethodHandle._InvokeMethodFast(IRuntimeMethodInfo method, Object target, Object[] arguments, SignatureStruct& sig, MethodAttributes methodAttributes, RuntimeType typeOwner)
    at System.RuntimeMethodHandle.InvokeMethodFast(IRuntimeMethodInfo method, Object target, Object[] arguments, Signature sig, MethodAttributes methodAttributes, RuntimeType typeOwner)
    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture, Boolean skipVisibilityChecks)
    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    at OpenQA.Selenium.Support.PageObjects.PageFactory.ProxiedWebElementInterceptor.Intercept(IInvocation invocation)
    at Castle.DynamicProxy.AbstractInvocation.Proceed()
    at Castle.Proxies.IWrapsElementProxy.Click()

---

It works fine on other browsers.

Does Does Operadriver support WebDriver alert api?

Cheers,

**Comment by andreastt** [comment]
We don't support the WebDriver alert API yet.  I've added this to the README file in 459a459598.  Thanks for bringing it to my attention.

We do plan to support this in the future, though. (-:
