### ISSUE TITLE
org.openqa.selenium.WebDriverException: com.opera.core.systems.scope.exceptions.ResponseNotReceivedException: No response in a timely fashion

### ISSUE THREAD

**Issue by java-developer** [operasoftware/operaprestodriver#50]
Hello,

We are getting the following exception when we run our Selenium tests on Windows:

```
org.openqa.selenium.WebDriverException: com.opera.core.systems.scope.exceptions.ResponseNotReceivedException: No response in a timely fashion
Build info: version: '2.15.0', revision: '15105', time: '2011-12-08 12:59:39'
System info: os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_02'
Driver info: driver.version: OperaDriver
Build info: version: '2.15.0', revision: '15105', time: '2011-12-08 12:59:39'
System info: os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_02'
Driver info: driver.version: OperaDriver
at com.opera.core.systems.OperaDriver.start(OperaDriver.java:358)
at com.opera.core.systems.OperaDriver.<init>(OperaDriver.java:312)
at com.opera.core.systems.OperaDriver.<init>(OperaDriver.java:213)
...
Caused by: com.opera.core.systems.scope.exceptions.ResponseNotReceivedException: No response in a timely fashion
Build info: version: '2.15.0', revision: '15105', time: '2011-12-08 12:59:39'
System info: os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_02'
Driver info: driver.version: OperaDriver
at com.opera.core.systems.WaitState.pollResultItem(WaitState.java:435)
at com.opera.core.systems.WaitState.waitAndParseResult(WaitState.java:464)
at com.opera.core.systems.WaitState.waitForHandshake(WaitState.java:665)
at com.opera.core.systems.ScopeServices.waitForHandshake(ScopeServices.java:323)
at com.opera.core.systems.ScopeServices.init(ScopeServices.java:210)
at com.opera.core.systems.OperaDriver.init(OperaDriver.java:377)
at com.opera.core.systems.OperaDriver.start(OperaDriver.java:354)
... 30 more
```

It happens every time we run the tests via Ant (TestNG) and randomly from Eclipse (TestNG).

It does not happen on OSX or Linux.

Environment:

OS: Windows 7
Selenium: 2.15.0
OperaDriver: HEAD

Can you help?

Thanks,

Craig

**Comment by andreastt** [comment]
This happens right after OperaDriver attempts to start Opera, correct?  There's a 30 second handshake timeout when you start Opera.  Does starting Opera take over 30 seconds on your Windows setup?

**Comment by java-developer** [comment]
I'm sorry but the priorities have changed at my workplace and I'm no longer working on this. I'm happy for you to close it. Sorry to waste your time.
