### ISSUE TITLE
Opera 11.01 and below is not working properly with operadriver 

### ISSUE THREAD

**Issue by namrathar** [operasoftware/operaprestodriver#78]
I was trying to run very simply perl test case in opera browser 11.01 and below versions like 11.00, 10.64 and others, even if i add all capabilities that are mentioned in opera driver its not running the test properly. Its launching the browser but not creating the driver object. Is it possible to run tests on opera 10 and 9 using operadriver? 

Same test case is working fine form 11.10 to latest version of opera.

platform:Linux
Selenium-Remote-Driver-0.15.tar.gz
selenium-server-standalone-2.20.0.jar

use Selenium::Remote::Driver;
my $driver = new Selenium::Remote::Driver('browser_name' => 'opera','extra_capabilities' => {'opera.binary' => 'operawrapper','opera.profile' => '','opera.port' => '-1','opera.logging.level' => 'FINE',},);
$driver->get("http://www.google.com/");
print $driver->get_title();
$driver->quit();

12:33:21.576 INFO - Executing: org.openqa.selenium.remote.server.handler.Status@32bd65 at URL: /status)
12:33:21.576 INFO - Executing: org.openqa.selenium.remote.server.handler.Status@32bd65 at URL: /status)
12:33:21.577 INFO - Done: /status
12:33:21.577 INFO - Done: /status
12:33:21.580 INFO - Executing: [new session: {opera.binary=/home/likewise-open/VITBDC/na..., platform=ANY, opera.launcher=/.launcher, javascriptEnabled=true, acceptSslCerts=true, opera.host=localhost, browserName=opera, proxy={httpProxy=localhost:8080, pr..., opera.logging.level=FINE, opera.profile=, opera.port=-1, version=}] at URL: /session)
12:33:21.580 INFO - Executing: [new session: {opera.binary=/home/likewise-open/VITBDC/na..., platform=ANY, opera.launcher=/.launcher, javascriptEnabled=true, acceptSslCerts=true, opera.host=localhost, browserName=opera, proxy={httpProxy=localhost:8080, pr..., opera.logging.level=FINE, opera.profile=, opera.port=-1, version=}] at URL: /session)
12:33:21.583 CONFIG - Opera arguments: [-autotestmode]
12:33:21.583 CONFIG - Opera arguments: [-autotestmode]
12:33:21.583 CONFIG - launcher arguments: [-host, 127.0.0.1, -port, 2544, -console, -verbosity, FINE, -profile, desktop, -backend, software, -bin, /home/likewise-open/VITBDC/namrathar/operawrapper, -autotestmode]
12:33:21.583 CONFIG - launcher arguments: [-host, 127.0.0.1, -port, 2544, -console, -verbosity, FINE, -profile, desktop, -backend, software, -bin, /home/likewise-open/VITBDC/namrathar/operawrapper, -autotestmode]
12:33:21.659 DEBUG - launcher: Operalauncher starting with the following configuration:
12:33:21.659 DEBUG - launcher: Operalauncher starting with the following configuration:
12:33:21.659 DEBUG - launcher: -bin: /home/likewise-open/VITBDC/namrathar/operawrapper
12:33:21.659 DEBUG - launcher: -bin: /home/likewise-open/VITBDC/namrathar/operawrapper
12:33:21.659 DEBUG - launcher: -host: 127.0.0.1
12:33:21.659 DEBUG - launcher: -host: 127.0.0.1
12:33:21.660 DEBUG - launcher: -port: 2544
12:33:21.660 DEBUG - launcher: -port: 2544
12:33:21.666 DEBUG - Waiting for launcher connection on port 2544
12:33:21.666 DEBUG - Waiting for launcher connection on port 2544
12:33:21.668 DEBUG - launcher: Blank screenshot has MD5: 0x6f5e1a4118e2d7f6f5f4a3a0ba14144c
12:33:21.668 DEBUG - launcher: Blank screenshot has MD5: 0x6f5e1a4118e2d7f6f5f4a3a0ba14144c
12:33:21.668 DEBUG - opera: [INFO]    --> Entering LauncherRunner::run
12:33:21.668 DEBUG - opera: [INFO]    --> Entering LauncherRunner::run
12:33:22.668 DEBUG - Got launcher connection from /127.0.0.1:36961
12:33:22.668 DEBUG - Got launcher connection from /127.0.0.1:36961
12:33:22.668 DEBUG - Connected with launcher on port 2544
12:33:22.668 DEBUG - Connected with launcher on port 2544
12:33:22.669 CONFIG - Capabilities [{platform=ANY, opera.binary=/home/likewise-open/VITBDC/namrathar/operawrapper, acceptSslCerts=true, javascriptEnabled=true, opera.host=localhost, opera.idle=false, browserName=opera, opera.autostart=true, opera.logging.file=null, opera.guess_binary_path=true, opera.logging.level=FINE, opera.profile=com.opera.core.systems.OperaProfile@19f03d7, version=, opera.launcher=/.launcher, proxy={httpProxy=localhost:8080, proxyType=manual}, opera.display=null, opera.product=core-gogi, opera.arguments=, opera.no_quit=false, opera.backend=software, opera.port=7001, opera.no_restart=false}]
12:33:22.669 CONFIG - Capabilities [{platform=ANY, opera.binary=/home/likewise-open/VITBDC/namrathar/operawrapper, acceptSslCerts=true, javascriptEnabled=true, opera.host=localhost, opera.idle=false, browserName=opera, opera.autostart=true, opera.logging.file=null, opera.guess_binary_path=true, opera.logging.level=FINE, opera.profile=com.opera.core.systems.OperaProfile@19f03d7, version=, opera.launcher=/.launcher, proxy={httpProxy=localhost:8080, proxyType=manual}, opera.display=null, opera.product=core-gogi, opera.arguments=, opera.no_quit=false, opera.backend=software, opera.port=7001, opera.no_restart=false}]
12:33:22.670 DEBUG - Instructing launcher to start Opera...
12:33:22.670 DEBUG - Instructing launcher to start Opera...
12:33:22.772 DEBUG - Opera launched through launcher
12:33:22.772 DEBUG - Opera launched through launcher
12:33:52.773 DEBUG - Shutting down STP connection listener
12:33:52.773 DEBUG - Shutting down STP connection listener
12:33:52.773 DEBUG - OperaDriver shutting down
12:33:52.773 DEBUG - OperaDriver shutting down
12:33:52.773 DEBUG - Shutting down launcher
12:33:52.773 DEBUG - Shutting down launcher
12:33:52.775 WARN - Exception thrown
java.util.concurrent.ExecutionException: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '2.20.0', revision: '16008', time: '2012-02-27 19:03:04'
System info: os.name: 'Linux', os.arch: 'i386', os.version: '2.6.32-40-generic', java.version: '1.6.0_26'
Driver info: driver.version: unknown
    at java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:222)
    at java.util.concurrent.FutureTask.get(FutureTask.java:83)
    at org.openqa.selenium.remote.server.DefaultSession.execute(DefaultSession.java:139)
    at org.openqa.selenium.remote.server.DefaultSession.<init>(DefaultSession.java:108)
    at org.openqa.selenium.remote.server.DefaultSession.createSession(DefaultSession.java:86)
    at org.openqa.selenium.remote.server.DefaultDriverSessions.newSession(DefaultDriverSessions.java:87)
    at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:62)
    at org.openqa.selenium.remote.server.rest.ResultConfig.handle(ResultConfig.java:196)
    at org.openqa.selenium.remote.server.DriverServlet.handleRequest(DriverServlet.java:580)
    at org.openqa.selenium.remote.server.DriverServlet.doPost(DriverServlet.java:531)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    at org.openqa.selenium.remote.server.DriverServlet.service(DriverServlet.java:503)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.openqa.jetty.jetty.servlet.ServletHolder.handle(ServletHolder.java:428)
    at org.openqa.jetty.jetty.servlet.ServletHandler.dispatch(ServletHandler.java:677)
    at org.openqa.jetty.jetty.servlet.ServletHandler.handle(ServletHandler.java:568)
    at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1530)
    at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1482)
    at org.openqa.jetty.http.HttpServer.service(HttpServer.java:909)
    at org.openqa.jetty.http.HttpConnection.service(HttpConnection.java:820)
    at org.openqa.jetty.http.HttpConnection.handleNext(HttpConnection.java:986)
    at org.openqa.jetty.http.HttpConnection.handle(HttpConnection.java:837)
    at org.openqa.jetty.http.SocketListener.handleConnection(SocketListener.java:243)
    at org.openqa.jetty.util.ThreadedServer.handle(ThreadedServer.java:357)
    at org.openqa.jetty.util.ThreadPool$PoolThread.run(ThreadPool.java:534)
Caused by: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '2.20.0', revision: '16008', time: '2012-02-27 19:03:04'
System info: os.name: 'Linux', os.arch: 'i386', os.version: '2.6.32-40-generic', java.version: '1.6.0_26'
Driver info: driver.version: unknown
    at org.openqa.selenium.remote.server.DefaultDriverFactory.callConstructor(DefaultDriverFactory.java:73)
    at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance(DefaultDriverFactory.java:57)
    at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:177)
    at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:1)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:662)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
    at org.openqa.selenium.remote.server.DefaultDriverFactory.callConstructor(DefaultDriverFactory.java:63)
    ... 8 more
Caused by: org.openqa.selenium.WebDriverException: com.opera.core.systems.scope.exceptions.ResponseNotReceivedException: No response in a timely fashion
Build info: version: '2.20.0', revision: '16008', time: '2012-02-27 19:03:04'
System info: os.name: 'Linux', os.arch: 'i386', os.version: '2.6.32-40-generic', java.version: '1.6.0_26'
Driver info: driver.version: OperaDriver
Build info: version: '2.20.0', revision: '16008', time: '2012-02-27 19:03:04'
System info: os.name: 'Linux', os.arch: 'i386', os.version: '2.6.32-40-generic', java.version: '1.6.0_26'
Driver info: driver.version: OperaDriver
    at com.opera.core.systems.OperaDriver.start(OperaDriver.java:379)
    at com.opera.core.systems.OperaDriver.<init>(OperaDriver.java:330)
    ... 13 more
Caused by: com.opera.core.systems.scope.exceptions.ResponseNotReceivedException: No response in a timely fashion
Build info: version: '2.20.0', revision: '16008', time: '2012-02-27 19:03:04'
System info: os.name: 'Linux', os.arch: 'i386', os.version: '2.6.32-40-generic', java.version: '1.6.0_26'
Driver info: driver.version: OperaDriver
    at com.opera.core.systems.WaitState.pollResultItem(WaitState.java:435)
    at com.opera.core.systems.WaitState.waitAndParseResult(WaitState.java:464)
    at com.opera.core.systems.WaitState.waitForHandshake(WaitState.java:665)
    at com.opera.core.systems.ScopeServices.waitForHandshake(ScopeServices.java:323)
    at com.opera.core.systems.ScopeServices.init(ScopeServices.java:210)
    at com.opera.core.systems.OperaDriver.init(OperaDriver.java:398)
    at com.opera.core.systems.OperaDriver.start(OperaDriver.java:375)
    ... 14 more
12:33:52.777 WARN - Exception: No response in a timely fashion
Build info: version: '2.20.0', revision: '16008', time: '2012-02-27 19:03:04'
System info: os.name: 'Linux', os.arch: 'i386', os.version: '2.6.32-40-generic', java.version: '1.6.0_26'
Driver info: driver.version: OperaDriver

**Comment by andreastt** [comment]
I don't think it's essential for us to provide support for Operas as old as back to version 11.  If it works, that's nice.  But not a requirement.  I suspect that you can get this to work by tweaking the required service versions in OperaDriver, and please feel free to submit a patch if you can get that working.
